import type { NextPage } from "next"
import Head from "next/head"
import Image from "next/image"
import styles from "../styles/Home.module.css"
import { useQuery } from "@apollo/client"
import { GET_POSTS } from "../libs/queries"
import { Suspense } from "react"
import Relatives from "../components/relatives"
import dynamic from "next/dynamic"
import Link from "next/link"
// import Test from "../components/test"
const Test = dynamic(() => import("../components/test"), {
  suspense: true,
})

const Home: NextPage = () => {
  // if (loading) {
  //   return <p>...loading posts</p>
  // }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p>post</p>
        <Suspense fallback={<div>Loading...</div>}>
          <Test />
        </Suspense>

        <p className={styles.description}>
          Get started by editing{" "}
          <code className={styles.code}>pages/index.tsx</code>
        </p>

        <Link href="/posts">All posts</Link>

        {/* relatives */}
        <p className={styles.description}>relativesList</p>
        <Relatives />
        {/* relatives */}
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
